'use client'
import { createContext, useContext, useState, useEffect } from 'react'

export type Lang = 'fr' | 'en' | 'es' | 'zh' | 'de' | 'ko' | 'ru' | 'ar'

export const LANGUAGES: { code: Lang; name: string; flag: string; dir?: 'rtl' }[] = [
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
]

// ============================================================
// TRADUCTIONS COMPLÈTES
// ============================================================
export const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.sectors': 'Formations',
    'nav.marketplace': 'Marketplace',
    'nav.alerts': 'Alertes',
    'nav.subscriptions': 'Abonnements',
    'nav.search': 'Rechercher',
    'nav.cart': 'Mon panier',
    'nav.login': 'Connexion',
    'nav.myspace': 'Mon espace',
    'nav.orders': 'Mes commandes',
    'nav.admin': 'Administration',
    'nav.logout': 'Deconnexion',

    // Auth
    'auth.login': 'Se connecter',
    'auth.register': "S'inscrire",
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgot': 'Oublie ?',
    'auth.connecting': 'Connexion...',
    'auth.profile': 'Quel est votre profil ?',
    'auth.learner': 'Je veux apprendre',
    'auth.learner_desc': 'Acces gratuit a toutes les formations securite',
    'auth.company': 'Je suis une entreprise',
    'auth.company_desc': 'Vente de materiel securite, EPI, formations',
    'auth.create_account': 'Creer mon compte',
    'auth.creating': 'Creation...',
    'auth.back_to_site': 'Retour au site',
    'auth.firstname': 'Prenom',
    'auth.lastname': 'Nom',
    'auth.company_name': "Nom de l'entreprise",
    'auth.activity': "Domaine d'activite",
    'auth.phone': 'Telephone',
    'auth.location': 'Localisation',
    'auth.terms': 'En continuant, vous acceptez nos',
    'auth.terms_link': 'CGU',
    'auth.back': 'Retour',
    'auth.confirm_sent': 'Compte cree ! Verifiez votre email pour confirmer votre compte, puis connectez-vous.',
    'auth.go_login': 'Aller a la connexion',
    'auth.one_domain': 'Une entreprise est specialisee dans un seul domaine.',

    // Homepage
    'home.hero_badge': 'Formation · Prevention · Securite',
    'home.hero_title1': 'LA SECURITE AU',
    'home.hero_title2': 'TRAVAIL EN AFRIQUE',
    'home.hero_desc': "Formations gratuites certifiees, alertes en temps reel et marketplace d'equipements pour tous les secteurs professionnels d'Afrique de l'Ouest.",
    'home.hero_cta1': 'Commencer gratuitement',
    'home.hero_cta2': 'Voir les secteurs',
    'home.stat_trainings': 'Formations disponibles',
    'home.stat_sectors': 'Secteurs couverts',
    'home.stat_learners': 'Apprenants actifs',
    'home.stat_alerts': 'Alertes publiees',
    'home.sectors_badge': 'Formations par secteur',
    'home.sectors_title': 'Votre secteur,',
    'home.sectors_title2': 'vos risques',
    'home.sectors_desc': 'Des contenus specialises pour chaque metier — videos, documents, FAQ et alertes adaptees a votre domaine.',
    'home.sectors_cta': 'Voir tous les secteurs',
    'home.alerts_badge': 'Alertes en temps reel',
    'home.alerts_title': 'Restez informé,',
    'home.alerts_title2': 'restez en securite',
    'home.alerts_cta': 'Toutes les alertes',
    'home.marketplace_badge': 'Marketplace securite',
    'home.marketplace_title': 'Equipements &',
    'home.marketplace_title2': 'Services HSE',
    'home.marketplace_desc': 'Trouvez des equipements certifies, formations et services HSE aupres de fournisseurs verifies.',
    'home.marketplace_cta': 'Explorer le marketplace',
    'home.cta_title': 'Pret a commencer ?',
    'home.cta_desc': 'Rejoignez des milliers de professionnels qui se forment gratuitement.',
    'home.cta_btn': 'Creer un compte gratuit',

    // Sectors
    'sectors.title': 'Secteurs de formation',
    'sectors.desc': 'Choisissez votre domaine pour acceder aux formations adaptees',
    'sectors.trainings': 'formations',
    'sectors.start': 'Commencer',
    'sectors.videos': 'Videos',
    'sectors.docs': 'Documents',
    'sectors.faq': 'FAQ',

    // Marketplace
    'market.title': 'Marketplace Securite',
    'market.desc': 'Trouvez equipements et prestataires certifies pres de chez vous.',
    'market.search': 'Rechercher EPI, formation, service...',
    'market.publish': 'Publier une annonce',
    'market.add_to_cart': 'Ajouter',
    'market.on_quote': 'Sur devis',
    'market.ask': 'Demander',
    'market.added_cart': 'Article ajoute au panier !',
    'market.certified': 'Certifie',
    'market.no_results': 'Aucune annonce trouvee',
    'market.add_product': 'Ajouter un produit ou service',

    // Cart
    'cart.title': 'Mon Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.empty_desc': 'Parcourez le marketplace pour trouver des equipements de securite.',
    'cart.explore': 'Explorer le marketplace',
    'cart.summary': 'Resume',
    'cart.total': 'Total',
    'cart.checkout': 'Passer la commande',
    'cart.continue': 'Continuer mes achats',
    'cart.your_info': 'Vos informations',
    'cart.confirm_order': 'Confirmer la commande',
    'cart.sending': 'Envoi...',
    'cart.order_confirmed': 'Commande confirmee !',
    'cart.order_desc': 'Les vendeurs vous contacteront directement par telephone ou email.',
    'cart.back_shopping': 'Continuer mes achats',

    // Alerts
    'alerts.title': 'Alertes Securite',
    'alerts.desc': 'Restez informe des dangers et incidents dans votre secteur',
    'alerts.all': 'Toutes',
    'alerts.active': 'Actives',
    'alerts.archived': 'Archivees',
    'alerts.no_results': 'Aucune alerte trouvee',

    // Dashboard
    'dash.welcome': 'Bienvenue sur Think Safety !',
    'dash.welcome_desc': "Votre compte est pret. Choisissez un secteur d'activite pour commencer votre premiere formation gratuitement.",
    'dash.choose_sector': 'Choisir mon premier secteur',
    'dash.popular': 'Secteurs populaires',
    'dash.my_trainings': 'Mes formations',
    'dash.my_certs': 'Mes certificats',
    'dash.followed': 'Formations suivies',
    'dash.completed': 'Terminees',
    'dash.in_progress': 'En cours',
    'dash.certificates': 'Certificats',

    // Subscriptions
    'sub.title': 'Choisissez votre abonnement',
    'sub.for_companies': 'Pour les entreprises',
    'sub.monthly': 'Mensuel',
    'sub.annual': 'Annuel',
    'sub.free': 'Gratuit',
    'sub.most_popular': 'Plus populaire',
    'sub.start_free': 'Commencer gratuitement',
    'sub.choose': 'Choisir',
    'sub.faq': 'Questions frequentes',

    // Common
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.create': 'Creer',
    'common.publish': 'Publier',
    'common.draft': 'Brouillon',
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succes',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.all': 'Tous',
    'common.add': 'Ajouter',
    'common.view_all': 'Voir tout',
    'common.see_site': 'Voir le site',
    'common.logout': 'Deconnexion',

    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Utilisateurs',
    'admin.companies': 'Entreprises',
    'admin.contents': 'Contenus',
    'admin.add_content': 'Ajouter contenu',
    'admin.alerts': 'Alertes',
    'admin.marketplace': 'Marketplace',
    'admin.orders': 'Commandes',
    'admin.subscriptions': 'Abonnements',
    'admin.payments': 'Config Paiements',
    'admin.settings': 'Parametres',
    'admin.documentation': 'Documentation Dev',
    'admin.new_content': 'Nouveau contenu',
    'admin.connected_as': 'Connecte en tant que',

    // Theme
    'theme.dark': 'Sombre',
    'theme.light': 'Clair',
    'theme.auto': 'Auto',

    // Maintenance
    'maintenance.title': 'Site en maintenance',
    'maintenance.desc': "Nous effectuons des ameliorations pour vous offrir une meilleure experience. Nous serons de retour tres bientot.",
    'maintenance.working': 'Travaux en cours...',
    'maintenance.admin_access': 'Acces administrateur',
  },

  en: {
    'nav.home': 'Home',
    'nav.sectors': 'Training',
    'nav.marketplace': 'Marketplace',
    'nav.alerts': 'Alerts',
    'nav.subscriptions': 'Subscriptions',
    'nav.search': 'Search',
    'nav.cart': 'My cart',
    'nav.login': 'Login',
    'nav.myspace': 'My space',
    'nav.orders': 'My orders',
    'nav.admin': 'Administration',
    'nav.logout': 'Logout',

    'auth.login': 'Sign in',
    'auth.register': 'Sign up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgot': 'Forgot?',
    'auth.connecting': 'Connecting...',
    'auth.profile': 'What is your profile?',
    'auth.learner': 'I want to learn',
    'auth.learner_desc': 'Free access to all safety training',
    'auth.company': 'I am a company',
    'auth.company_desc': 'Safety equipment, PPE, certified training',
    'auth.create_account': 'Create my account',
    'auth.creating': 'Creating...',
    'auth.back_to_site': 'Back to site',
    'auth.firstname': 'First name',
    'auth.lastname': 'Last name',
    'auth.company_name': 'Company name',
    'auth.activity': 'Field of activity',
    'auth.phone': 'Phone',
    'auth.location': 'Location',
    'auth.terms': 'By continuing, you accept our',
    'auth.terms_link': 'Terms',
    'auth.back': 'Back',
    'auth.confirm_sent': 'Account created! Check your email to confirm your account, then log in.',
    'auth.go_login': 'Go to login',
    'auth.one_domain': 'A company specializes in one domain only.',

    'home.hero_badge': 'Training · Prevention · Safety',
    'home.hero_title1': 'WORKPLACE SAFETY',
    'home.hero_title2': 'IN AFRICA',
    'home.hero_desc': 'Free certified training, real-time alerts and equipment marketplace for all professional sectors in West Africa.',
    'home.hero_cta1': 'Start for free',
    'home.hero_cta2': 'View sectors',
    'home.stat_trainings': 'Available trainings',
    'home.stat_sectors': 'Sectors covered',
    'home.stat_learners': 'Active learners',
    'home.stat_alerts': 'Published alerts',
    'home.sectors_badge': 'Training by sector',
    'home.sectors_title': 'Your sector,',
    'home.sectors_title2': 'your risks',
    'home.sectors_desc': 'Specialized content for each profession — videos, documents, FAQ and alerts tailored to your field.',
    'home.sectors_cta': 'View all sectors',
    'home.alerts_badge': 'Real-time alerts',
    'home.alerts_title': 'Stay informed,',
    'home.alerts_title2': 'stay safe',
    'home.alerts_cta': 'All alerts',
    'home.marketplace_badge': 'Safety marketplace',
    'home.marketplace_title': 'Equipment &',
    'home.marketplace_title2': 'HSE Services',
    'home.marketplace_desc': 'Find certified equipment, training and HSE services from verified suppliers.',
    'home.marketplace_cta': 'Explore marketplace',
    'home.cta_title': 'Ready to start?',
    'home.cta_desc': 'Join thousands of professionals training for free.',
    'home.cta_btn': 'Create free account',

    'sectors.title': 'Training sectors',
    'sectors.desc': 'Choose your field to access tailored training',
    'sectors.trainings': 'trainings',
    'sectors.start': 'Start',
    'sectors.videos': 'Videos',
    'sectors.docs': 'Documents',
    'sectors.faq': 'FAQ',

    'market.title': 'Safety Marketplace',
    'market.desc': 'Find certified equipment and providers near you.',
    'market.search': 'Search PPE, training, service...',
    'market.publish': 'Post an ad',
    'market.add_to_cart': 'Add',
    'market.on_quote': 'On quote',
    'market.ask': 'Request',
    'market.added_cart': 'Item added to cart!',
    'market.certified': 'Certified',
    'market.no_results': 'No ads found',
    'market.add_product': 'Add a product or service',

    'cart.title': 'My Cart',
    'cart.empty': 'Your cart is empty',
    'cart.empty_desc': 'Browse the marketplace to find safety equipment.',
    'cart.explore': 'Explore marketplace',
    'cart.summary': 'Summary',
    'cart.total': 'Total',
    'cart.checkout': 'Place order',
    'cart.continue': 'Continue shopping',
    'cart.your_info': 'Your information',
    'cart.confirm_order': 'Confirm order',
    'cart.sending': 'Sending...',
    'cart.order_confirmed': 'Order confirmed!',
    'cart.order_desc': 'Sellers will contact you directly by phone or email.',
    'cart.back_shopping': 'Continue shopping',

    'alerts.title': 'Safety Alerts',
    'alerts.desc': 'Stay informed about hazards and incidents in your sector',
    'alerts.all': 'All',
    'alerts.active': 'Active',
    'alerts.archived': 'Archived',
    'alerts.no_results': 'No alerts found',

    'dash.welcome': 'Welcome to Think Safety!',
    'dash.welcome_desc': 'Your account is ready. Choose a sector to start your first free training.',
    'dash.choose_sector': 'Choose my first sector',
    'dash.popular': 'Popular sectors',
    'dash.my_trainings': 'My trainings',
    'dash.my_certs': 'My certificates',
    'dash.followed': 'Followed trainings',
    'dash.completed': 'Completed',
    'dash.in_progress': 'In progress',
    'dash.certificates': 'Certificates',

    'sub.title': 'Choose your subscription',
    'sub.for_companies': 'For companies',
    'sub.monthly': 'Monthly',
    'sub.annual': 'Annual',
    'sub.free': 'Free',
    'sub.most_popular': 'Most popular',
    'sub.start_free': 'Start for free',
    'sub.choose': 'Choose',
    'sub.faq': 'Frequently asked questions',

    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.publish': 'Publish',
    'common.draft': 'Draft',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.add': 'Add',
    'common.view_all': 'View all',
    'common.see_site': 'View site',
    'common.logout': 'Logout',

    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.companies': 'Companies',
    'admin.contents': 'Contents',
    'admin.add_content': 'Add content',
    'admin.alerts': 'Alerts',
    'admin.marketplace': 'Marketplace',
    'admin.orders': 'Orders',
    'admin.subscriptions': 'Subscriptions',
    'admin.payments': 'Payment Config',
    'admin.settings': 'Settings',
    'admin.documentation': 'Dev Documentation',
    'admin.new_content': 'New content',
    'admin.connected_as': 'Connected as',

    'theme.dark': 'Dark',
    'theme.light': 'Light',
    'theme.auto': 'Auto',

    'maintenance.title': 'Site under maintenance',
    'maintenance.desc': 'We are making improvements to offer you a better experience. We will be back very soon.',
    'maintenance.working': 'Work in progress...',
    'maintenance.admin_access': 'Administrator access',
  },

  es: {
    'nav.home': 'Inicio',
    'nav.sectors': 'Formaciones',
    'nav.marketplace': 'Mercado',
    'nav.alerts': 'Alertas',
    'nav.subscriptions': 'Suscripciones',
    'nav.search': 'Buscar',
    'nav.cart': 'Mi carrito',
    'nav.login': 'Iniciar sesion',
    'nav.myspace': 'Mi espacio',
    'nav.orders': 'Mis pedidos',
    'nav.admin': 'Administracion',
    'nav.logout': 'Cerrar sesion',
    'auth.login': 'Iniciar sesion',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electronico',
    'auth.password': 'Contrasena',
    'auth.forgot': 'Olvidado?',
    'auth.connecting': 'Conectando...',
    'auth.profile': 'Cual es su perfil?',
    'auth.learner': 'Quiero aprender',
    'auth.learner_desc': 'Acceso gratuito a todas las formaciones de seguridad',
    'auth.company': 'Soy una empresa',
    'auth.company_desc': 'Venta de equipos de seguridad, EPIs, formaciones',
    'auth.create_account': 'Crear mi cuenta',
    'auth.creating': 'Creando...',
    'auth.back_to_site': 'Volver al sitio',
    'auth.firstname': 'Nombre',
    'auth.lastname': 'Apellido',
    'auth.company_name': 'Nombre de la empresa',
    'auth.activity': 'Campo de actividad',
    'auth.phone': 'Telefono',
    'auth.location': 'Ubicacion',
    'auth.terms': 'Al continuar, aceptas nuestros',
    'auth.terms_link': 'Terminos',
    'auth.back': 'Atras',
    'auth.confirm_sent': 'Cuenta creada! Verifica tu email para confirmar tu cuenta y luego inicia sesion.',
    'auth.go_login': 'Ir al inicio de sesion',
    'auth.one_domain': 'Una empresa se especializa en un solo dominio.',
    'home.hero_badge': 'Formacion · Prevencion · Seguridad',
    'home.hero_title1': 'SEGURIDAD LABORAL',
    'home.hero_title2': 'EN AFRICA',
    'home.hero_desc': 'Formaciones gratuitas certificadas, alertas en tiempo real y mercado de equipos para todos los sectores profesionales de Africa Occidental.',
    'home.hero_cta1': 'Empezar gratis',
    'home.hero_cta2': 'Ver sectores',
    'home.stat_trainings': 'Formaciones disponibles',
    'home.stat_sectors': 'Sectores cubiertos',
    'home.stat_learners': 'Estudiantes activos',
    'home.stat_alerts': 'Alertas publicadas',
    'home.sectors_badge': 'Formacion por sector',
    'home.sectors_title': 'Tu sector,',
    'home.sectors_title2': 'tus riesgos',
    'home.sectors_desc': 'Contenido especializado para cada profesion — videos, documentos, FAQ y alertas adaptadas a tu campo.',
    'home.sectors_cta': 'Ver todos los sectores',
    'home.alerts_badge': 'Alertas en tiempo real',
    'home.alerts_title': 'Mantente informado,',
    'home.alerts_title2': 'mantente seguro',
    'home.alerts_cta': 'Todas las alertas',
    'home.marketplace_badge': 'Mercado de seguridad',
    'home.marketplace_title': 'Equipos y',
    'home.marketplace_title2': 'Servicios HSE',
    'home.marketplace_desc': 'Encuentra equipos certificados, formaciones y servicios HSE de proveedores verificados.',
    'home.marketplace_cta': 'Explorar el mercado',
    'home.cta_title': 'Listo para empezar?',
    'home.cta_desc': 'Unete a miles de profesionales que se forman gratis.',
    'home.cta_btn': 'Crear cuenta gratis',
    'sectors.title': 'Sectores de formacion',
    'sectors.desc': 'Elige tu campo para acceder a formaciones adaptadas',
    'sectors.trainings': 'formaciones',
    'sectors.start': 'Empezar',
    'sectors.videos': 'Videos',
    'sectors.docs': 'Documentos',
    'sectors.faq': 'FAQ',
    'market.title': 'Mercado de Seguridad',
    'market.desc': 'Encuentra equipos y proveedores certificados cerca de ti.',
    'market.search': 'Buscar EPIs, formacion, servicio...',
    'market.publish': 'Publicar anuncio',
    'market.add_to_cart': 'Agregar',
    'market.on_quote': 'Bajo presupuesto',
    'market.ask': 'Solicitar',
    'market.added_cart': 'Articulo agregado al carrito!',
    'market.certified': 'Certificado',
    'market.no_results': 'No se encontraron anuncios',
    'market.add_product': 'Agregar producto o servicio',
    'cart.title': 'Mi Carrito',
    'cart.empty': 'Tu carrito esta vacio',
    'cart.empty_desc': 'Explora el mercado para encontrar equipos de seguridad.',
    'cart.explore': 'Explorar mercado',
    'cart.summary': 'Resumen',
    'cart.total': 'Total',
    'cart.checkout': 'Realizar pedido',
    'cart.continue': 'Continuar comprando',
    'cart.your_info': 'Tu informacion',
    'cart.confirm_order': 'Confirmar pedido',
    'cart.sending': 'Enviando...',
    'cart.order_confirmed': 'Pedido confirmado!',
    'cart.order_desc': 'Los vendedores te contactaran directamente por telefono o email.',
    'cart.back_shopping': 'Continuar comprando',
    'alerts.title': 'Alertas de Seguridad',
    'alerts.desc': 'Mantente informado sobre peligros e incidentes en tu sector',
    'alerts.all': 'Todas',
    'alerts.active': 'Activas',
    'alerts.archived': 'Archivadas',
    'alerts.no_results': 'No se encontraron alertas',
    'dash.welcome': 'Bienvenido a Think Safety!',
    'dash.welcome_desc': 'Tu cuenta esta lista. Elige un sector para comenzar tu primera formacion gratis.',
    'dash.choose_sector': 'Elegir mi primer sector',
    'dash.popular': 'Sectores populares',
    'dash.my_trainings': 'Mis formaciones',
    'dash.my_certs': 'Mis certificados',
    'dash.followed': 'Formaciones seguidas',
    'dash.completed': 'Completadas',
    'dash.in_progress': 'En progreso',
    'dash.certificates': 'Certificados',
    'sub.title': 'Elige tu suscripcion',
    'sub.for_companies': 'Para empresas',
    'sub.monthly': 'Mensual',
    'sub.annual': 'Anual',
    'sub.free': 'Gratis',
    'sub.most_popular': 'Mas popular',
    'sub.start_free': 'Empezar gratis',
    'sub.choose': 'Elegir',
    'sub.faq': 'Preguntas frecuentes',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Crear',
    'common.publish': 'Publicar',
    'common.draft': 'Borrador',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Exito',
    'common.back': 'Atras',
    'common.next': 'Siguiente',
    'common.close': 'Cerrar',
    'common.yes': 'Si',
    'common.no': 'No',
    'common.all': 'Todos',
    'common.add': 'Agregar',
    'common.view_all': 'Ver todo',
    'common.see_site': 'Ver sitio',
    'common.logout': 'Cerrar sesion',
    'admin.dashboard': 'Panel de control',
    'admin.users': 'Usuarios',
    'admin.companies': 'Empresas',
    'admin.contents': 'Contenidos',
    'admin.add_content': 'Agregar contenido',
    'admin.alerts': 'Alertas',
    'admin.marketplace': 'Mercado',
    'admin.orders': 'Pedidos',
    'admin.subscriptions': 'Suscripciones',
    'admin.payments': 'Config Pagos',
    'admin.settings': 'Configuracion',
    'admin.documentation': 'Documentacion Dev',
    'admin.new_content': 'Nuevo contenido',
    'admin.connected_as': 'Conectado como',
    'theme.dark': 'Oscuro',
    'theme.light': 'Claro',
    'theme.auto': 'Auto',
    'maintenance.title': 'Sitio en mantenimiento',
    'maintenance.desc': 'Estamos realizando mejoras para ofrecerte una mejor experiencia. Volvemos muy pronto.',
    'maintenance.working': 'Trabajo en progreso...',
    'maintenance.admin_access': 'Acceso de administrador',
  },

  zh: {
    'nav.home': '首页',
    'nav.sectors': '培训',
    'nav.marketplace': '市场',
    'nav.alerts': '警报',
    'nav.subscriptions': '订阅',
    'nav.search': '搜索',
    'nav.cart': '我的购物车',
    'nav.login': '登录',
    'nav.myspace': '我的空间',
    'nav.orders': '我的订单',
    'nav.admin': '管理',
    'nav.logout': '退出',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.forgot': '忘记了?',
    'auth.connecting': '连接中...',
    'auth.profile': '您的档案是什么?',
    'auth.learner': '我想学习',
    'auth.learner_desc': '免费获取所有安全培训',
    'auth.company': '我是一家公司',
    'auth.company_desc': '安全设备、个人防护装备、认证培训销售',
    'auth.create_account': '创建我的账户',
    'auth.creating': '创建中...',
    'auth.back_to_site': '返回网站',
    'auth.firstname': '名字',
    'auth.lastname': '姓氏',
    'auth.company_name': '公司名称',
    'auth.activity': '活动领域',
    'auth.phone': '电话',
    'auth.location': '位置',
    'auth.terms': '继续即表示您接受我们的',
    'auth.terms_link': '条款',
    'auth.back': '返回',
    'auth.confirm_sent': '账户已创建！请检查您的邮箱确认账户，然后登录。',
    'auth.go_login': '前往登录',
    'auth.one_domain': '一家公司只能专注于一个领域。',
    'home.hero_badge': '培训 · 预防 · 安全',
    'home.hero_title1': '非洲职业',
    'home.hero_title2': '安全培训',
    'home.hero_desc': '为西非所有职业部门提供免费认证培训、实时警报和设备市场。',
    'home.hero_cta1': '免费开始',
    'home.hero_cta2': '查看行业',
    'home.stat_trainings': '可用培训',
    'home.stat_sectors': '覆盖行业',
    'home.stat_learners': '活跃学员',
    'home.stat_alerts': '已发布警报',
    'home.sectors_badge': '按行业培训',
    'home.sectors_title': '您的行业,',
    'home.sectors_title2': '您的风险',
    'home.sectors_desc': '为每个职业提供专业内容 — 视频、文档、常见问题和针对您领域的警报。',
    'home.sectors_cta': '查看所有行业',
    'home.alerts_badge': '实时警报',
    'home.alerts_title': '保持知情,',
    'home.alerts_title2': '保持安全',
    'home.alerts_cta': '所有警报',
    'home.marketplace_badge': '安全市场',
    'home.marketplace_title': '设备和',
    'home.marketplace_title2': 'HSE服务',
    'home.marketplace_desc': '从经过验证的供应商处找到认证设备、培训和HSE服务。',
    'home.marketplace_cta': '探索市场',
    'home.cta_title': '准备开始了吗?',
    'home.cta_desc': '加入数千名免费培训的专业人士。',
    'home.cta_btn': '创建免费账户',
    'sectors.title': '培训行业',
    'sectors.desc': '选择您的领域以获取量身定制的培训',
    'sectors.trainings': '培训',
    'sectors.start': '开始',
    'sectors.videos': '视频',
    'sectors.docs': '文件',
    'sectors.faq': '常见问题',
    'market.title': '安全市场',
    'market.desc': '在您附近找到经认证的设备和服务提供商。',
    'market.search': '搜索个人防护装备、培训、服务...',
    'market.publish': '发布广告',
    'market.add_to_cart': '添加',
    'market.on_quote': '报价',
    'market.ask': '询问',
    'market.added_cart': '商品已添加到购物车！',
    'market.certified': '认证',
    'market.no_results': '未找到广告',
    'market.add_product': '添加产品或服务',
    'cart.title': '我的购物车',
    'cart.empty': '您的购物车是空的',
    'cart.empty_desc': '浏览市场寻找安全设备。',
    'cart.explore': '探索市场',
    'cart.summary': '摘要',
    'cart.total': '总计',
    'cart.checkout': '下订单',
    'cart.continue': '继续购物',
    'cart.your_info': '您的信息',
    'cart.confirm_order': '确认订单',
    'cart.sending': '发送中...',
    'cart.order_confirmed': '订单已确认！',
    'cart.order_desc': '卖家将直接通过电话或电子邮件联系您。',
    'cart.back_shopping': '继续购物',
    'alerts.title': '安全警报',
    'alerts.desc': '随时了解您所在行业的危险和事件',
    'alerts.all': '全部',
    'alerts.active': '活跃',
    'alerts.archived': '已归档',
    'alerts.no_results': '未找到警报',
    'dash.welcome': '欢迎来到Think Safety！',
    'dash.welcome_desc': '您的账户已准备好。选择一个行业开始您的第一次免费培训。',
    'dash.choose_sector': '选择我的第一个行业',
    'dash.popular': '热门行业',
    'dash.my_trainings': '我的培训',
    'dash.my_certs': '我的证书',
    'dash.followed': '已关注培训',
    'dash.completed': '已完成',
    'dash.in_progress': '进行中',
    'dash.certificates': '证书',
    'sub.title': '选择您的订阅',
    'sub.for_companies': '针对企业',
    'sub.monthly': '每月',
    'sub.annual': '每年',
    'sub.free': '免费',
    'sub.most_popular': '最受欢迎',
    'sub.start_free': '免费开始',
    'sub.choose': '选择',
    'sub.faq': '常见问题',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.publish': '发布',
    'common.draft': '草稿',
    'common.search': '搜索',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.back': '返回',
    'common.next': '下一步',
    'common.close': '关闭',
    'common.yes': '是',
    'common.no': '否',
    'common.all': '全部',
    'common.add': '添加',
    'common.view_all': '查看全部',
    'common.see_site': '查看网站',
    'common.logout': '退出',
    'admin.dashboard': '仪表板',
    'admin.users': '用户',
    'admin.companies': '企业',
    'admin.contents': '内容',
    'admin.add_content': '添加内容',
    'admin.alerts': '警报',
    'admin.marketplace': '市场',
    'admin.orders': '订单',
    'admin.subscriptions': '订阅',
    'admin.payments': '支付配置',
    'admin.settings': '设置',
    'admin.documentation': '开发文档',
    'admin.new_content': '新内容',
    'admin.connected_as': '已连接为',
    'theme.dark': '深色',
    'theme.light': '浅色',
    'theme.auto': '自动',
    'maintenance.title': '网站维护中',
    'maintenance.desc': '我们正在进行改进，为您提供更好的体验。我们很快就会回来。',
    'maintenance.working': '工作进行中...',
    'maintenance.admin_access': '管理员访问',
  },

  de: {
    'nav.home': 'Startseite',
    'nav.sectors': 'Schulungen',
    'nav.marketplace': 'Marktplatz',
    'nav.alerts': 'Warnungen',
    'nav.subscriptions': 'Abonnements',
    'nav.search': 'Suchen',
    'nav.cart': 'Mein Warenkorb',
    'nav.login': 'Anmelden',
    'nav.myspace': 'Mein Bereich',
    'nav.orders': 'Meine Bestellungen',
    'nav.admin': 'Verwaltung',
    'nav.logout': 'Abmelden',
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgot': 'Vergessen?',
    'auth.connecting': 'Verbinden...',
    'auth.profile': 'Was ist Ihr Profil?',
    'auth.learner': 'Ich möchte lernen',
    'auth.learner_desc': 'Kostenloser Zugang zu allen Sicherheitsschulungen',
    'auth.company': 'Ich bin ein Unternehmen',
    'auth.company_desc': 'Sicherheitsausrüstung, PSA, zertifizierte Schulungen',
    'auth.create_account': 'Mein Konto erstellen',
    'auth.creating': 'Erstellen...',
    'auth.back_to_site': 'Zurück zur Website',
    'auth.firstname': 'Vorname',
    'auth.lastname': 'Nachname',
    'auth.company_name': 'Unternehmensname',
    'auth.activity': 'Tätigkeitsbereich',
    'auth.phone': 'Telefon',
    'auth.location': 'Standort',
    'auth.terms': 'Mit dem Fortfahren akzeptieren Sie unsere',
    'auth.terms_link': 'AGB',
    'auth.back': 'Zurück',
    'auth.confirm_sent': 'Konto erstellt! Überprüfen Sie Ihre E-Mail zur Bestätigung.',
    'auth.go_login': 'Zur Anmeldung',
    'auth.one_domain': 'Ein Unternehmen ist auf einen Bereich spezialisiert.',
    'home.hero_badge': 'Schulung · Prävention · Sicherheit',
    'home.hero_title1': 'ARBEITSSICHERHEIT',
    'home.hero_title2': 'IN AFRIKA',
    'home.hero_desc': 'Kostenlose zertifizierte Schulungen, Echtzeit-Warnungen und Ausrüstungsmarktplatz für alle Berufssektoren in Westafrika.',
    'home.hero_cta1': 'Kostenlos starten',
    'home.hero_cta2': 'Sektoren ansehen',
    'home.stat_trainings': 'Verfügbare Schulungen',
    'home.stat_sectors': 'Abgedeckte Sektoren',
    'home.stat_learners': 'Aktive Lernende',
    'home.stat_alerts': 'Veröffentlichte Warnungen',
    'home.sectors_badge': 'Schulung nach Sektor',
    'home.sectors_title': 'Ihr Sektor,',
    'home.sectors_title2': 'Ihre Risiken',
    'home.sectors_desc': 'Spezialisierte Inhalte für jeden Beruf — Videos, Dokumente, FAQ.',
    'home.sectors_cta': 'Alle Sektoren anzeigen',
    'home.alerts_badge': 'Echtzeit-Warnungen',
    'home.alerts_title': 'Bleiben Sie informiert,',
    'home.alerts_title2': 'bleiben Sie sicher',
    'home.alerts_cta': 'Alle Warnungen',
    'home.marketplace_badge': 'Sicherheitsmarktplatz',
    'home.marketplace_title': 'Ausrüstung &',
    'home.marketplace_title2': 'HSE-Dienste',
    'home.marketplace_desc': 'Finden Sie zertifizierte Ausrüstung, Schulungen und HSE-Dienste.',
    'home.marketplace_cta': 'Marktplatz erkunden',
    'home.cta_title': 'Bereit anzufangen?',
    'home.cta_desc': 'Schließen Sie sich Tausenden von Fachleuten an.',
    'home.cta_btn': 'Kostenloses Konto erstellen',
    'sectors.title': 'Schulungssektoren',
    'sectors.desc': 'Wählen Sie Ihr Fachgebiet',
    'sectors.trainings': 'Schulungen',
    'sectors.start': 'Beginnen',
    'sectors.videos': 'Videos',
    'sectors.docs': 'Dokumente',
    'sectors.faq': 'FAQ',
    'market.title': 'Sicherheitsmarktplatz',
    'market.desc': 'Finden Sie zertifizierte Ausrüstung in Ihrer Nähe.',
    'market.search': 'PSA, Schulung, Service suchen...',
    'market.publish': 'Anzeige aufgeben',
    'market.add_to_cart': 'Hinzufügen',
    'market.on_quote': 'Auf Anfrage',
    'market.ask': 'Anfragen',
    'market.added_cart': 'Artikel zum Warenkorb hinzugefügt!',
    'market.certified': 'Zertifiziert',
    'market.no_results': 'Keine Anzeigen gefunden',
    'market.add_product': 'Produkt oder Dienst hinzufügen',
    'cart.title': 'Mein Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.empty_desc': 'Durchsuchen Sie den Marktplatz.',
    'cart.explore': 'Marktplatz erkunden',
    'cart.summary': 'Zusammenfassung',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Bestellen',
    'cart.continue': 'Weiter einkaufen',
    'cart.your_info': 'Ihre Informationen',
    'cart.confirm_order': 'Bestellung bestätigen',
    'cart.sending': 'Senden...',
    'cart.order_confirmed': 'Bestellung bestätigt!',
    'cart.order_desc': 'Verkäufer kontaktieren Sie direkt.',
    'cart.back_shopping': 'Weiter einkaufen',
    'alerts.title': 'Sicherheitswarnungen',
    'alerts.desc': 'Bleiben Sie über Gefahren informiert',
    'alerts.all': 'Alle',
    'alerts.active': 'Aktiv',
    'alerts.archived': 'Archiviert',
    'alerts.no_results': 'Keine Warnungen gefunden',
    'dash.welcome': 'Willkommen bei Think Safety!',
    'dash.welcome_desc': 'Ihr Konto ist bereit. Wählen Sie einen Sektor.',
    'dash.choose_sector': 'Ersten Sektor wählen',
    'dash.popular': 'Beliebte Sektoren',
    'dash.my_trainings': 'Meine Schulungen',
    'dash.my_certs': 'Meine Zertifikate',
    'dash.followed': 'Verfolgte Schulungen',
    'dash.completed': 'Abgeschlossen',
    'dash.in_progress': 'In Bearbeitung',
    'dash.certificates': 'Zertifikate',
    'sub.title': 'Wählen Sie Ihr Abonnement',
    'sub.for_companies': 'Für Unternehmen',
    'sub.monthly': 'Monatlich',
    'sub.annual': 'Jährlich',
    'sub.free': 'Kostenlos',
    'sub.most_popular': 'Beliebteste',
    'sub.start_free': 'Kostenlos starten',
    'sub.choose': 'Wählen',
    'sub.faq': 'Häufig gestellte Fragen',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.publish': 'Veröffentlichen',
    'common.draft': 'Entwurf',
    'common.search': 'Suchen',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.close': 'Schließen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.all': 'Alle',
    'common.add': 'Hinzufügen',
    'common.view_all': 'Alle anzeigen',
    'common.see_site': 'Website anzeigen',
    'common.logout': 'Abmelden',
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Benutzer',
    'admin.companies': 'Unternehmen',
    'admin.contents': 'Inhalte',
    'admin.add_content': 'Inhalt hinzufügen',
    'admin.alerts': 'Warnungen',
    'admin.marketplace': 'Marktplatz',
    'admin.orders': 'Bestellungen',
    'admin.subscriptions': 'Abonnements',
    'admin.payments': 'Zahlungskonfig',
    'admin.settings': 'Einstellungen',
    'admin.documentation': 'Entwicklerdoku',
    'admin.new_content': 'Neuer Inhalt',
    'admin.connected_as': 'Verbunden als',
    'theme.dark': 'Dunkel',
    'theme.light': 'Hell',
    'theme.auto': 'Auto',
    'maintenance.title': 'Website in Wartung',
    'maintenance.desc': 'Wir nehmen Verbesserungen vor. Wir sind bald zurück.',
    'maintenance.working': 'Arbeit im Gange...',
    'maintenance.admin_access': 'Administratorzugang',
  },

  ko: {
    'nav.home': '홈',
    'nav.sectors': '교육',
    'nav.marketplace': '마켓플레이스',
    'nav.alerts': '알림',
    'nav.subscriptions': '구독',
    'nav.search': '검색',
    'nav.cart': '내 장바구니',
    'nav.login': '로그인',
    'nav.myspace': '내 공간',
    'nav.orders': '내 주문',
    'nav.admin': '관리',
    'nav.logout': '로그아웃',
    'auth.login': '로그인',
    'auth.register': '회원가입',
    'auth.email': '이메일',
    'auth.password': '비밀번호',
    'auth.forgot': '잊어버렸나요?',
    'auth.connecting': '연결 중...',
    'auth.profile': '프로필이 무엇인가요?',
    'auth.learner': '배우고 싶습니다',
    'auth.learner_desc': '모든 안전 교육에 무료 접근',
    'auth.company': '저는 기업입니다',
    'auth.company_desc': '안전 장비, PPE, 인증 교육 판매',
    'auth.create_account': '계정 만들기',
    'auth.creating': '생성 중...',
    'auth.back_to_site': '사이트로 돌아가기',
    'auth.firstname': '이름',
    'auth.lastname': '성',
    'auth.company_name': '회사명',
    'auth.activity': '활동 분야',
    'auth.phone': '전화',
    'auth.location': '위치',
    'auth.terms': '계속함으로써 당사',
    'auth.terms_link': '약관에 동의합니다',
    'auth.back': '뒤로',
    'auth.confirm_sent': '계정이 생성되었습니다! 이메일을 확인하여 계정을 확인하세요.',
    'auth.go_login': '로그인으로 이동',
    'auth.one_domain': '회사는 하나의 도메인에 특화되어 있습니다.',
    'home.hero_badge': '교육 · 예방 · 안전',
    'home.hero_title1': '아프리카의',
    'home.hero_title2': '직장 안전',
    'home.hero_desc': '서아프리카 모든 전문 분야를 위한 무료 인증 교육, 실시간 알림, 장비 마켓플레이스.',
    'home.hero_cta1': '무료로 시작하기',
    'home.hero_cta2': '분야 보기',
    'home.stat_trainings': '이용 가능한 교육',
    'home.stat_sectors': '다루는 분야',
    'home.stat_learners': '활성 학습자',
    'home.stat_alerts': '게시된 알림',
    'home.sectors_badge': '분야별 교육',
    'home.sectors_title': '당신의 분야,',
    'home.sectors_title2': '당신의 위험',
    'home.sectors_desc': '각 직업에 맞는 전문 콘텐츠 — 비디오, 문서, FAQ.',
    'home.sectors_cta': '모든 분야 보기',
    'home.alerts_badge': '실시간 알림',
    'home.alerts_title': '정보를 얻고,',
    'home.alerts_title2': '안전하게 지내세요',
    'home.alerts_cta': '모든 알림',
    'home.marketplace_badge': '안전 마켓플레이스',
    'home.marketplace_title': '장비 및',
    'home.marketplace_title2': 'HSE 서비스',
    'home.marketplace_desc': '검증된 공급업체에서 인증 장비, 교육 및 HSE 서비스를 찾으세요.',
    'home.marketplace_cta': '마켓플레이스 탐색',
    'home.cta_title': '시작할 준비가 되셨나요?',
    'home.cta_desc': '무료로 교육받는 수천 명의 전문가에 합류하세요.',
    'home.cta_btn': '무료 계정 만들기',
    'sectors.title': '교육 분야',
    'sectors.desc': '맞춤 교육에 접근하려면 분야를 선택하세요',
    'sectors.trainings': '교육',
    'sectors.start': '시작',
    'sectors.videos': '동영상',
    'sectors.docs': '문서',
    'sectors.faq': 'FAQ',
    'market.title': '안전 마켓플레이스',
    'market.desc': '근처에서 인증된 장비와 서비스 제공업체를 찾으세요.',
    'market.search': 'PPE, 교육, 서비스 검색...',
    'market.publish': '광고 게시',
    'market.add_to_cart': '추가',
    'market.on_quote': '견적 요청',
    'market.ask': '문의',
    'market.added_cart': '장바구니에 추가되었습니다!',
    'market.certified': '인증',
    'market.no_results': '광고를 찾을 수 없습니다',
    'market.add_product': '제품 또는 서비스 추가',
    'cart.title': '내 장바구니',
    'cart.empty': '장바구니가 비어 있습니다',
    'cart.empty_desc': '마켓플레이스에서 안전 장비를 찾아보세요.',
    'cart.explore': '마켓플레이스 탐색',
    'cart.summary': '요약',
    'cart.total': '합계',
    'cart.checkout': '주문하기',
    'cart.continue': '계속 쇼핑',
    'cart.your_info': '내 정보',
    'cart.confirm_order': '주문 확인',
    'cart.sending': '전송 중...',
    'cart.order_confirmed': '주문 확인됨!',
    'cart.order_desc': '판매자가 직접 연락드립니다.',
    'cart.back_shopping': '계속 쇼핑',
    'alerts.title': '안전 알림',
    'alerts.desc': '분야의 위험 및 사고에 대한 정보를 받으세요',
    'alerts.all': '전체',
    'alerts.active': '활성',
    'alerts.archived': '보관됨',
    'alerts.no_results': '알림을 찾을 수 없습니다',
    'dash.welcome': 'Think Safety에 오신 것을 환영합니다!',
    'dash.welcome_desc': '계정이 준비되었습니다. 첫 무료 교육을 시작할 분야를 선택하세요.',
    'dash.choose_sector': '첫 분야 선택',
    'dash.popular': '인기 분야',
    'dash.my_trainings': '내 교육',
    'dash.my_certs': '내 자격증',
    'dash.followed': '팔로우한 교육',
    'dash.completed': '완료됨',
    'dash.in_progress': '진행 중',
    'dash.certificates': '자격증',
    'sub.title': '구독 선택',
    'sub.for_companies': '기업용',
    'sub.monthly': '월간',
    'sub.annual': '연간',
    'sub.free': '무료',
    'sub.most_popular': '가장 인기',
    'sub.start_free': '무료로 시작',
    'sub.choose': '선택',
    'sub.faq': '자주 묻는 질문',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.create': '만들기',
    'common.publish': '게시',
    'common.draft': '초안',
    'common.search': '검색',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.back': '뒤로',
    'common.next': '다음',
    'common.close': '닫기',
    'common.yes': '예',
    'common.no': '아니요',
    'common.all': '전체',
    'common.add': '추가',
    'common.view_all': '전체 보기',
    'common.see_site': '사이트 보기',
    'common.logout': '로그아웃',
    'admin.dashboard': '대시보드',
    'admin.users': '사용자',
    'admin.companies': '기업',
    'admin.contents': '콘텐츠',
    'admin.add_content': '콘텐츠 추가',
    'admin.alerts': '알림',
    'admin.marketplace': '마켓플레이스',
    'admin.orders': '주문',
    'admin.subscriptions': '구독',
    'admin.payments': '결제 설정',
    'admin.settings': '설정',
    'admin.documentation': '개발자 문서',
    'admin.new_content': '새 콘텐츠',
    'admin.connected_as': '연결됨:',
    'theme.dark': '어두운',
    'theme.light': '밝은',
    'theme.auto': '자동',
    'maintenance.title': '사이트 점검 중',
    'maintenance.desc': '더 나은 경험을 위해 개선 작업 중입니다. 곧 돌아옵니다.',
    'maintenance.working': '작업 진행 중...',
    'maintenance.admin_access': '관리자 접근',
  },

  ru: {
    'nav.home': 'Главная',
    'nav.sectors': 'Обучение',
    'nav.marketplace': 'Маркетплейс',
    'nav.alerts': 'Оповещения',
    'nav.subscriptions': 'Подписки',
    'nav.search': 'Поиск',
    'nav.cart': 'Моя корзина',
    'nav.login': 'Войти',
    'nav.myspace': 'Мой кабинет',
    'nav.orders': 'Мои заказы',
    'nav.admin': 'Администрация',
    'nav.logout': 'Выйти',
    'auth.login': 'Войти',
    'auth.register': 'Зарегистрироваться',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.forgot': 'Забыли?',
    'auth.connecting': 'Подключение...',
    'auth.profile': 'Какой у вас профиль?',
    'auth.learner': 'Хочу учиться',
    'auth.learner_desc': 'Бесплатный доступ ко всем курсам по безопасности',
    'auth.company': 'Я компания',
    'auth.company_desc': 'Продажа оборудования безопасности, СИЗ, обучение',
    'auth.create_account': 'Создать аккаунт',
    'auth.creating': 'Создание...',
    'auth.back_to_site': 'Вернуться на сайт',
    'auth.firstname': 'Имя',
    'auth.lastname': 'Фамилия',
    'auth.company_name': 'Название компании',
    'auth.activity': 'Область деятельности',
    'auth.phone': 'Телефон',
    'auth.location': 'Местоположение',
    'auth.terms': 'Продолжая, вы принимаете наши',
    'auth.terms_link': 'Условия',
    'auth.back': 'Назад',
    'auth.confirm_sent': 'Аккаунт создан! Проверьте email для подтверждения.',
    'auth.go_login': 'Перейти к входу',
    'auth.one_domain': 'Компания специализируется в одной области.',
    'home.hero_badge': 'Обучение · Профилактика · Безопасность',
    'home.hero_title1': 'ОХРАНА ТРУДА',
    'home.hero_title2': 'В АФРИКЕ',
    'home.hero_desc': 'Бесплатное сертифицированное обучение, оповещения в реальном времени и маркетплейс оборудования для Западной Африки.',
    'home.hero_cta1': 'Начать бесплатно',
    'home.hero_cta2': 'Просмотр секторов',
    'home.stat_trainings': 'Доступных курсов',
    'home.stat_sectors': 'Охваченных секторов',
    'home.stat_learners': 'Активных учеников',
    'home.stat_alerts': 'Опубликованных оповещений',
    'home.sectors_badge': 'Обучение по секторам',
    'home.sectors_title': 'Ваш сектор,',
    'home.sectors_title2': 'ваши риски',
    'home.sectors_desc': 'Специализированный контент для каждой профессии — видео, документы, FAQ.',
    'home.sectors_cta': 'Все секторы',
    'home.alerts_badge': 'Оповещения в реальном времени',
    'home.alerts_title': 'Будьте в курсе,',
    'home.alerts_title2': 'оставайтесь в безопасности',
    'home.alerts_cta': 'Все оповещения',
    'home.marketplace_badge': 'Маркетплейс безопасности',
    'home.marketplace_title': 'Оборудование и',
    'home.marketplace_title2': 'услуги HSE',
    'home.marketplace_desc': 'Найдите сертифицированное оборудование и услуги HSE.',
    'home.marketplace_cta': 'Исследовать маркетплейс',
    'home.cta_title': 'Готовы начать?',
    'home.cta_desc': 'Присоединяйтесь к тысячам профессионалов.',
    'home.cta_btn': 'Создать бесплатный аккаунт',
    'sectors.title': 'Секторы обучения',
    'sectors.desc': 'Выберите область для доступа к специализированному обучению',
    'sectors.trainings': 'курсов',
    'sectors.start': 'Начать',
    'sectors.videos': 'Видео',
    'sectors.docs': 'Документы',
    'sectors.faq': 'FAQ',
    'market.title': 'Маркетплейс безопасности',
    'market.desc': 'Найдите сертифицированное оборудование рядом с вами.',
    'market.search': 'Поиск СИЗ, обучения, услуг...',
    'market.publish': 'Разместить объявление',
    'market.add_to_cart': 'Добавить',
    'market.on_quote': 'По запросу',
    'market.ask': 'Запросить',
    'market.added_cart': 'Товар добавлен в корзину!',
    'market.certified': 'Сертифицировано',
    'market.no_results': 'Объявления не найдены',
    'market.add_product': 'Добавить товар или услугу',
    'cart.title': 'Моя корзина',
    'cart.empty': 'Ваша корзина пуста',
    'cart.empty_desc': 'Просмотрите маркетплейс для поиска оборудования.',
    'cart.explore': 'Исследовать маркетплейс',
    'cart.summary': 'Итог',
    'cart.total': 'Итого',
    'cart.checkout': 'Оформить заказ',
    'cart.continue': 'Продолжить покупки',
    'cart.your_info': 'Ваша информация',
    'cart.confirm_order': 'Подтвердить заказ',
    'cart.sending': 'Отправка...',
    'cart.order_confirmed': 'Заказ подтвержден!',
    'cart.order_desc': 'Продавцы свяжутся с вами напрямую.',
    'cart.back_shopping': 'Продолжить покупки',
    'alerts.title': 'Оповещения безопасности',
    'alerts.desc': 'Будьте в курсе опасностей в вашем секторе',
    'alerts.all': 'Все',
    'alerts.active': 'Активные',
    'alerts.archived': 'Архивные',
    'alerts.no_results': 'Оповещения не найдены',
    'dash.welcome': 'Добро пожаловать в Think Safety!',
    'dash.welcome_desc': 'Ваш аккаунт готов. Выберите сектор для начала обучения.',
    'dash.choose_sector': 'Выбрать первый сектор',
    'dash.popular': 'Популярные секторы',
    'dash.my_trainings': 'Моё обучение',
    'dash.my_certs': 'Мои сертификаты',
    'dash.followed': 'Отслеживаемые курсы',
    'dash.completed': 'Завершены',
    'dash.in_progress': 'В процессе',
    'dash.certificates': 'Сертификаты',
    'sub.title': 'Выберите подписку',
    'sub.for_companies': 'Для компаний',
    'sub.monthly': 'Ежемесячно',
    'sub.annual': 'Ежегодно',
    'sub.free': 'Бесплатно',
    'sub.most_popular': 'Самый популярный',
    'sub.start_free': 'Начать бесплатно',
    'sub.choose': 'Выбрать',
    'sub.faq': 'Часто задаваемые вопросы',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.create': 'Создать',
    'common.publish': 'Опубликовать',
    'common.draft': 'Черновик',
    'common.search': 'Поиск',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.close': 'Закрыть',
    'common.yes': 'Да',
    'common.no': 'Нет',
    'common.all': 'Все',
    'common.add': 'Добавить',
    'common.view_all': 'Просмотреть все',
    'common.see_site': 'Посмотреть сайт',
    'common.logout': 'Выйти',
    'admin.dashboard': 'Панель управления',
    'admin.users': 'Пользователи',
    'admin.companies': 'Компании',
    'admin.contents': 'Контент',
    'admin.add_content': 'Добавить контент',
    'admin.alerts': 'Оповещения',
    'admin.marketplace': 'Маркетплейс',
    'admin.orders': 'Заказы',
    'admin.subscriptions': 'Подписки',
    'admin.payments': 'Настройка оплаты',
    'admin.settings': 'Настройки',
    'admin.documentation': 'Документация разработчика',
    'admin.new_content': 'Новый контент',
    'admin.connected_as': 'Подключен как',
    'theme.dark': 'Тёмная',
    'theme.light': 'Светлая',
    'theme.auto': 'Авто',
    'maintenance.title': 'Сайт на обслуживании',
    'maintenance.desc': 'Мы вносим улучшения. Скоро вернёмся.',
    'maintenance.working': 'Работа в процессе...',
    'maintenance.admin_access': 'Доступ администратора',
  },

  ar: {
    'nav.home': 'الرئيسية',
    'nav.sectors': 'التدريب',
    'nav.marketplace': 'السوق',
    'nav.alerts': 'التنبيهات',
    'nav.subscriptions': 'الاشتراكات',
    'nav.search': 'بحث',
    'nav.cart': 'سلة التسوق',
    'nav.login': 'تسجيل الدخول',
    'nav.myspace': 'مساحتي',
    'nav.orders': 'طلباتي',
    'nav.admin': 'الإدارة',
    'nav.logout': 'تسجيل الخروج',
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgot': 'نسيت؟',
    'auth.connecting': 'جارٍ الاتصال...',
    'auth.profile': 'ما هو ملفك الشخصي؟',
    'auth.learner': 'أريد التعلم',
    'auth.learner_desc': 'وصول مجاني لجميع دورات السلامة',
    'auth.company': 'أنا شركة',
    'auth.company_desc': 'بيع معدات السلامة، والتدريب المعتمد',
    'auth.create_account': 'إنشاء حسابي',
    'auth.creating': 'جارٍ الإنشاء...',
    'auth.back_to_site': 'العودة إلى الموقع',
    'auth.firstname': 'الاسم الأول',
    'auth.lastname': 'اسم العائلة',
    'auth.company_name': 'اسم الشركة',
    'auth.activity': 'مجال النشاط',
    'auth.phone': 'الهاتف',
    'auth.location': 'الموقع',
    'auth.terms': 'بالمتابعة، فإنك توافق على',
    'auth.terms_link': 'شروط الخدمة',
    'auth.back': 'رجوع',
    'auth.confirm_sent': 'تم إنشاء الحساب! تحقق من بريدك الإلكتروني للتأكيد.',
    'auth.go_login': 'الذهاب لتسجيل الدخول',
    'auth.one_domain': 'تتخصص الشركة في مجال واحد فقط.',
    'home.hero_badge': 'تدريب · وقاية · سلامة',
    'home.hero_title1': 'السلامة المهنية',
    'home.hero_title2': 'في أفريقيا',
    'home.hero_desc': 'تدريب مجاني معتمد، وتنبيهات فورية، وسوق معدات لجميع القطاعات المهنية في غرب أفريقيا.',
    'home.hero_cta1': 'ابدأ مجاناً',
    'home.hero_cta2': 'عرض القطاعات',
    'home.stat_trainings': 'دورات متاحة',
    'home.stat_sectors': 'قطاعات مغطاة',
    'home.stat_learners': 'متعلمون نشطون',
    'home.stat_alerts': 'تنبيهات منشورة',
    'home.sectors_badge': 'التدريب حسب القطاع',
    'home.sectors_title': 'قطاعك،',
    'home.sectors_title2': 'مخاطرك',
    'home.sectors_desc': 'محتوى متخصص لكل مهنة — فيديوهات، مستندات، أسئلة شائعة.',
    'home.sectors_cta': 'عرض كل القطاعات',
    'home.alerts_badge': 'تنبيهات فورية',
    'home.alerts_title': 'ابقَ مطلعاً،',
    'home.alerts_title2': 'ابقَ آمناً',
    'home.alerts_cta': 'كل التنبيهات',
    'home.marketplace_badge': 'سوق السلامة',
    'home.marketplace_title': 'معدات و',
    'home.marketplace_title2': 'خدمات HSE',
    'home.marketplace_desc': 'اعثر على معدات معتمدة وخدمات HSE من موردين موثوقين.',
    'home.marketplace_cta': 'استكشاف السوق',
    'home.cta_title': 'هل أنت مستعد للبدء؟',
    'home.cta_desc': 'انضم إلى آلاف المهنيين الذين يتدربون مجاناً.',
    'home.cta_btn': 'إنشاء حساب مجاني',
    'sectors.title': 'قطاعات التدريب',
    'sectors.desc': 'اختر مجالك للوصول إلى تدريب مخصص',
    'sectors.trainings': 'دورات',
    'sectors.start': 'ابدأ',
    'sectors.videos': 'فيديوهات',
    'sectors.docs': 'مستندات',
    'sectors.faq': 'أسئلة شائعة',
    'market.title': 'سوق السلامة',
    'market.desc': 'اعثر على معدات ومزودين معتمدين بالقرب منك.',
    'market.search': 'البحث عن معدات، تدريب، خدمة...',
    'market.publish': 'نشر إعلان',
    'market.add_to_cart': 'أضف',
    'market.on_quote': 'بالتسعيرة',
    'market.ask': 'استفسر',
    'market.added_cart': 'تمت إضافة المنتج إلى السلة!',
    'market.certified': 'معتمد',
    'market.no_results': 'لم يتم العثور على إعلانات',
    'market.add_product': 'إضافة منتج أو خدمة',
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.empty_desc': 'تصفح السوق للعثور على معدات السلامة.',
    'cart.explore': 'استكشاف السوق',
    'cart.summary': 'ملخص',
    'cart.total': 'المجموع',
    'cart.checkout': 'تقديم الطلب',
    'cart.continue': 'مواصلة التسوق',
    'cart.your_info': 'معلوماتك',
    'cart.confirm_order': 'تأكيد الطلب',
    'cart.sending': 'جارٍ الإرسال...',
    'cart.order_confirmed': 'تم تأكيد الطلب!',
    'cart.order_desc': 'سيتصل بك البائعون مباشرة.',
    'cart.back_shopping': 'مواصلة التسوق',
    'alerts.title': 'تنبيهات السلامة',
    'alerts.desc': 'ابقَ مطلعاً على المخاطر في قطاعك',
    'alerts.all': 'الكل',
    'alerts.active': 'نشطة',
    'alerts.archived': 'مؤرشفة',
    'alerts.no_results': 'لم يتم العثور على تنبيهات',
    'dash.welcome': 'مرحباً بك في Think Safety!',
    'dash.welcome_desc': 'حسابك جاهز. اختر قطاعاً لبدء أول تدريب مجاني لك.',
    'dash.choose_sector': 'اختر قطاعي الأول',
    'dash.popular': 'القطاعات الشائعة',
    'dash.my_trainings': 'تدريباتي',
    'dash.my_certs': 'شهاداتي',
    'dash.followed': 'الدورات المتابعة',
    'dash.completed': 'مكتملة',
    'dash.in_progress': 'جارية',
    'dash.certificates': 'الشهادات',
    'sub.title': 'اختر اشتراكك',
    'sub.for_companies': 'للشركات',
    'sub.monthly': 'شهري',
    'sub.annual': 'سنوي',
    'sub.free': 'مجاني',
    'sub.most_popular': 'الأكثر شيوعاً',
    'sub.start_free': 'ابدأ مجاناً',
    'sub.choose': 'اختر',
    'sub.faq': 'الأسئلة الشائعة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.create': 'إنشاء',
    'common.publish': 'نشر',
    'common.draft': 'مسودة',
    'common.search': 'بحث',
    'common.loading': 'جارٍ التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.close': 'إغلاق',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.all': 'الكل',
    'common.add': 'إضافة',
    'common.view_all': 'عرض الكل',
    'common.see_site': 'عرض الموقع',
    'common.logout': 'تسجيل الخروج',
    'admin.dashboard': 'لوحة التحكم',
    'admin.users': 'المستخدمون',
    'admin.companies': 'الشركات',
    'admin.contents': 'المحتوى',
    'admin.add_content': 'إضافة محتوى',
    'admin.alerts': 'التنبيهات',
    'admin.marketplace': 'السوق',
    'admin.orders': 'الطلبات',
    'admin.subscriptions': 'الاشتراكات',
    'admin.payments': 'إعداد الدفع',
    'admin.settings': 'الإعدادات',
    'admin.documentation': 'وثائق المطور',
    'admin.new_content': 'محتوى جديد',
    'admin.connected_as': 'متصل كـ',
    'theme.dark': 'داكن',
    'theme.light': 'فاتح',
    'theme.auto': 'تلقائي',
    'maintenance.title': 'الموقع قيد الصيانة',
    'maintenance.desc': 'نحن نجري تحسينات لتقديم تجربة أفضل. سنعود قريباً.',
    'maintenance.working': 'العمل جارٍ...',
    'maintenance.admin_access': 'وصول المسؤول',
  },
}

// ============================================================
// CONTEXT
// ============================================================
interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'fr',
  setLang: () => {},
  t: (key) => key,
  isRTL: false,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('fr')

  useEffect(() => {
    const saved = (localStorage.getItem('ts_lang') as Lang) || 'fr'
    if (translations[saved]) setLangState(saved)
    applyLang(saved)
  }, [])

  function applyLang(l: Lang) {
    const langConfig = LANGUAGES.find(x => x.code === l)
    document.documentElement.lang = l
    document.documentElement.dir = langConfig?.dir || 'ltr'
  }

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('ts_lang', l)
    applyLang(l)
  }

  function t(key: string): string {
    return translations[lang]?.[key] || translations['fr']?.[key] || key
  }

  const isRTL = LANGUAGES.find(x => x.code === lang)?.dir === 'rtl'

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
